### ISSUE TITLE
Import and Export parity between Beaver Pocket & Beaver Notes (images)

### ISSUE THREAD

**Issue by Daniele-rolli** [Daniele-rolli/Beaver-pocket#7]

**Comment by Daniele-rolli** [comment]
Hey @bigshans, would you mind looking into the image component? I've been trying to achieve Import and Export parity between Beaver Pocket & Beaver Notes. However, images are a pain in the neck, as the app currently retrieves the image src using Capacitor.convertFileSrc, which creates a device-specific src. This src cannot be exported or imported on other devices, whether it's desktop or mobile.

**Comment by bigshans** [comment]
My pleasure.

**Comment by bigshans** [comment]
![图片](https://github.com/Daniele-rolli/Beaver-notes-pocket/assets/26884666/940a7d0e-ea12-481b-a4bb-c3aec07b6f66)

Like this?

**Comment by bigshans** [comment]
My solution is very simple.

Set a map to store the relation:

```typescript
  const handleImageUpload = (imageUrl: string, fileUri: string, filePath: string) => {
    imageMap.set(filePath, imageUrl);
    editor?.chain().setImage({ src: filePath, alt: fileUri }).run();
  };
```

Extend image render:

```typescript
[
  ImageResize.extend({
    addNodeView() {
      const viewer = this.parent?.() as any;
      return (props) => {
        const attrs = props.node.attrs;
        const node = { ...props.node, attrs: { ...attrs, src: ImageMap.get(attrs.src) || attrs.src } };
        const newProps = { ...props, node };
        console.log(newProps);
        return viewer(newProps);
      };
    }
  }),
]
```

**Comment by Daniele-rolli** [comment]
It looks great! But could you tell me where you got the ImageMap from? VScode keeps saying it can't find the name 'imageMap'.

**Comment by Daniele-rolli** [comment]
That's ok, take all the time you need. Thanks again for your help.
